name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Set up Node.js for testing
        uses: actions/setup-node@main
        with:
          node-version: "latest"
          
      - name: Install dependencies and run tests
        run: |
          cd ./msw-app
          npm install || { echo "Failed to install dependencies"; exit 1; }
          npm test || { echo "Tests failed"; exit 1; }

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Build Docker image and push to GitHub Container Registry
        run: |
          cd ./msw-app
          docker build -f ./Dockerfile -t ghcr.io/${{ github.repository }}/msw-app . || { echo "Failed to build Docker image"; exit 1; }
          docker push ghcr.io/${{ github.repository }}/msw-app || { echo "Failed to push Docker image"; exit 1; }
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      
    - name: Execute commands on EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        script: |
          # Remove old Docker containers
          sudo docker stop msw-app || { echo "Failed to stop container"; exit 1; }
          sudo docker rm msw-app || { echo "Failed to remove container"; exit 1; }
          
          # Remove old Docker images
          sudo docker image prune -a -f || true

          # Remove all stopped containers
          sudo docker container prune -f || true
          
          # Pull the latest Docker image
          sudo docker pull ghcr.io/${{ github.repository }}/msw-app:latest
          if [ $? -ne 0 ]; then
            echo "Failed to pull the Docker image"
            exit 1
          fi
          
          # Run the Docker container on port 80
          sudo docker run -d --name msw-app -p 80:3000 ghcr.io/${{ github.repository }}/msw-app:latest
