name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: "latest"
      - name: Install and test
        run: |
          cd ./msw-app
          npm install
          npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push
        run: |
          cd ./msw-app
          docker build -f Dockerfile -t ghcr.io/${{ github.repository }} .
          docker push ghcr.io/${{ github.repository }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        
      - name: Execute commands on EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            sudo docker pull docker pull ghcr.io/latest${{ github.repository }}/msw-app:latest
            sudo docker stop msw-app || true
            sudo docker rm msw-app || true
            sudo docker run -d --name msw-app -p 80:80 ghcr.io/latest${{ github.repository }}/msw-app:latest
